title: Agora Sei
encoding: UTF-8
timezone: America/Sao_Paulo
url: "https://agorasei.com.br"
sass:
  style: :compressed
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

# jekyll-archives:
#   enabled: all

compress_html:
  clippings: all
  comments: [""]
  endings: []
  profile: false
  blanklines: false
  ignore:
    envs: []
